### ISSUE TITLE
Differences between Progressive Prompt and LFPT5

### ISSUE THREAD

**Issue by CuongNN218** [arazd/ProgressivePrompts#1]
Dear authors,
Congratulations for your great effort to release source code. I really enjoyed your paper when I read it. However, I realized that the idea of progressive prompt is quite similar to the idea in Sec. 3.2.1 in LFPT 5 paper in which authors proposed to add a new set of learnable prompt tokens when a new task come, learned tokens from previous task are frozen, and all prior prompt tokens is concatenate with new ones in training a new task. The main different between these two is the use of embedding re-parameterization indicated in Sec. 3 in your paper. Am I correct? Feel free to correct me if I misunderstood.
P/s: And one more question about the ablation studies of the paper: Did you compare LFPT5 with Progressive Prompt w/o MLP and Progressive Prompt w MLP in the continual setting?
Thanks.

**Comment by arazd** [comment]
Thanks a lot for you questions / comments :) the key differences between Progressive Prompts and LFPT5 are: 
1) _Progressive Prompt_ trains and freezes a separate prompt for each **new task**. In contrast, _LFPT5_ "tunes additional prompt embeddings to learn a **new task type**", so a new prompt is dedicated for a new task type (generation / classification / NER), but the prompt tokens are shared for all tasks that belong to that particular task domain. Because of that, LFPT5 suffers from catastrophic forgetting within task type: as shown in Table 6 from LFPT5 paper, the classification accuracy on DBpedia task drops from 98% to 49% when task order is changed. This doesn't happen to Progressive Prompts since we don't change prompt embeddings for the learned tasks.
2)  Progressive Prompt concatenates newly learned prompt with previously learned frozen prompts, which helps to achieve forward transfer when learning new tasks. This is similar to in-context learning, with previously learned soft prompts acting as "knowledge base" for future tasks.
3) As you mentioned, we also apply MLP reparameterization to speed up training. We preserved the original LFPT5 setup (w/o MLP reparameterization) for fair comparison, but it might be a good future direction to try. However, the main issue with LFPT5 is that it suffers from forgetting, which reparameterization cannot alleviate. 

Hope this is helpful! Please let me know if you have more questions!
